-- ============================================================
-- Seed: Migrate CLIENTES-CONFIG.json → clients table
-- Run AFTER 001_auth_profiles.sql
-- ============================================================

INSERT INTO public.clients (slug, name, type, category, status, priority, location, specialty, contact, brand, celo_config, integrations)
VALUES
  (
    'dr-erico-servano',
    'Dr. Erico Servano',
    'B2B Professional Services',
    'Legal Consulting',
    'active',
    'premium',
    'Belo Horizonte, MG',
    'Direito de Harmonização Orofacial',
    '{"email":"contato@servanoadvogados.com","instagram":"@ericoservano","linkedin":"Erico Servano"}'::jsonb,
    '{"primaryColor":"#B8956A","darkColor":"#151515","style":"premium-classic-law"}'::jsonb,
    '{"clientId":"dr-erico-servano","adsPlatform":"meta","metaAdAccountId":"act_1397446335381640","metaPageId":"804491499425586","ghlLocationId":"MmKHrppeW0M8EQ4M1noj"}'::jsonb,
    '{}'::jsonb
  ),
  (
    'dra-vanessa-soares',
    'Dra. Vanessa Soares',
    'B2C Healthcare',
    'Medical Aesthetic Services',
    'active',
    'premium',
    'Belo Horizonte, MG',
    'Dermatologia e Medicina Estética',
    '{"email":"contato@dra-vanessasoares.com","instagram":"@dra.vanessasoares.bh","website":"www.dra-vanessasoares.com"}'::jsonb,
    '{"primaryColor":"#C4A96A","darkColor":"#1E3A3A","style":"premium-medical-aesthetic"}'::jsonb,
    '{"clientId":"dra-vanessa-soares","adsPlatform":"meta","metaAdAccountId":"act_659024227004356","metaPageId":"280473538472405"}'::jsonb,
    '{}'::jsonb
  ),
  (
    'estetica-gabrielleoliveira',
    'Estética Gabrielle Oliveira',
    'B2C Beauty Services',
    'Aesthetic and Beauty Services',
    'active',
    'growth',
    'Brasil (Nacional)',
    'Serviços de Beleza e Estética',
    '{"email":"gabrielle@estetica.com","instagram":"@estetica_gabrielleoliveira"}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'torre-1',
    'Torre 1',
    'Agency Client',
    NULL,
    'active',
    'standard',
    NULL,
    NULL,
    '{"email":"contato@torre1.com"}'::jsonb,
    '{}'::jsonb,
    '{"clientId":"torre-1","adsPlatform":"meta","metaAdAccountId":"act_4992030634193032","metaPageId":"837049336158107"}'::jsonb,
    '{}'::jsonb
  ),
  (
    'humbertoandradebr',
    'Humberto Andrade',
    NULL,
    NULL,
    'active',
    'standard',
    NULL,
    NULL,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'fourcred',
    'Fourcred',
    NULL,
    NULL,
    'active',
    'standard',
    NULL,
    NULL,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'prof-dr-humberto-andrade',
    'Prof. Dr. Humberto Andrade',
    'Education/Consulting',
    'Acadêmica/Consultoria',
    'active',
    'standard',
    NULL,
    NULL,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'dr-teste-simulacao',
    'Dr. Teste Simulação',
    NULL,
    NULL,
    'active',
    'standard',
    'São Paulo, SP',
    'Teste de Onboarding',
    '{"phone":"5511966137112","instagram":"@drtestesimulacao","email":"teste@syra.digital"}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{"groupJid":"120363425308600341@g.us","clickupListId":"901326173255"}'::jsonb
  ),
  (
    'dr-enio-leite',
    'Dr. Enio Leite',
    NULL,
    NULL,
    'active',
    'standard',
    NULL,
    NULL,
    '{"phone":"5527996566104","instagram":"https://www.instagram.com/drenioleite/"}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{"groupJid":"120363408200429131@g.us","clickupListId":"901326206577"}'::jsonb
  ),
  (
    'dr-cleugo-porto',
    'Dr. Cleugo Porto',
    'B2C Healthcare',
    'Medical Aesthetic Services',
    'active',
    'standard',
    'Alphaville, São Paulo',
    'Celulite, Lipedema, Harmonização Corporal',
    '{"email":"contato@drcleugo.com.br","phone":"+55 11 4195-5960","instagram":"@drcleugo"}'::jsonb,
    '{"primaryColor":"#D1A84B","darkColor":"#020202","style":"premium-dark-medical-aesthetic"}'::jsonb,
    '{}'::jsonb,
    '{"groupJid":"120363425170331329@g.us"}'::jsonb
  ),
  (
    'victor-jambeiro-martins',
    'Victor Jambeiro Martins',
    NULL,
    NULL,
    'active',
    'standard',
    NULL,
    NULL,
    '{"phone":"11934722779","instagram":"@vjmartins03"}'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb,
    '{"clickupListId":"901326261788"}'::jsonb
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  category = EXCLUDED.category,
  status = EXCLUDED.status,
  priority = EXCLUDED.priority,
  location = EXCLUDED.location,
  specialty = EXCLUDED.specialty,
  contact = EXCLUDED.contact,
  brand = EXCLUDED.brand,
  celo_config = EXCLUDED.celo_config,
  integrations = EXCLUDED.integrations;
