module.exports = {
  apps: [
    {
      name: 'nico-telegram',
      script: 'telegram-webhook-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/nico-telegram.error.log',
      out_file: 'logs/nico-telegram.out.log',
      merge_logs: true,
    },
    {
      name: 'nico-whatsapp',
      script: 'whatsapp-agent-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/nico-whatsapp.error.log',
      out_file: 'logs/nico-whatsapp.out.log',
      merge_logs: true,
    },
    {
      name: 'celo',
      script: 'celo-agent-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/celo.error.log',
      out_file: 'logs/celo.out.log',
      merge_logs: true,
    },
    {
      name: 'alex',
      script: 'alex-agent-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/alex.error.log',
      out_file: 'logs/alex.out.log',
      merge_logs: true,
    },
    {
      name: 'ghl-webhook',
      script: 'ghl-webhook-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/ghl.error.log',
      out_file: 'logs/ghl.out.log',
      merge_logs: true,
    },
    {
      name: 'iris',
      script: 'iris-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/iris.error.log',
      out_file: 'logs/iris.out.log',
      merge_logs: true,
    },
    {
      name: 'cold-outreach',
      script: 'cold-outreach-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/cold-outreach.error.log',
      out_file: 'logs/cold-outreach.out.log',
      merge_logs: true,
    },
    {
      name: 'syra-hub',
      script: 'syra-hub.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '200M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/syra-hub.error.log',
      out_file: 'logs/syra-hub.out.log',
      merge_logs: true,
    },
    {
      name: 'swipe-collector',
      script: 'swipe-collector.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/swipe-collector.error.log',
      out_file: 'logs/swipe-collector.out.log',
      merge_logs: true,
    },
    {
      name: 'scribe-watcher',
      script: 'scribe-watcher.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/scribe-watcher.error.log',
      out_file: 'logs/scribe-watcher.out.log',
      merge_logs: true,
    },
    {
      name: 'content-radar',
      script: 'content-radar-server.js',
      cwd: '/Users/ericsantos/meu-aios/meu-projeto',
      env_file: '.env',
      restart_delay: 5000,
      max_restarts: 10,
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/content-radar.error.log',
      out_file: 'logs/content-radar.out.log',
      merge_logs: true,
    },
  ],
};
