import {
  Brain, Megaphone, Paintbrush, Code2, TestTube2, Landmark,
  BarChart3, TrendingUp, Target, MessageSquare, Users, FileText,
  Workflow, Bot, Feather, Sparkles, ScrollText, Shield, Clipboard,
  Instagram, UserCheck,
} from 'lucide-react'
import type { AgentInfo } from '@/components/agents/agent-card'

export const DEPARTMENTS = {
  strategy: { label: 'Estratégia', color: '#60A5FA' },
  creative: { label: 'Criativo', color: '#C084FC' },
  tech: { label: 'Tech & Data', color: '#34D399' },
  operations: { label: 'Operações', color: '#FB923C' },
} as const

export const AGENTS: AgentInfo[] = [
  // Strategy
  {
    id: 'pm',
    name: 'PM',
    role: 'Project Manager',
    description: 'Gerencia projetos, sprints, roadmap e priorização de tarefas.',
    icon: Clipboard,
    color: '#5B8DEF',
    department: 'strategy',
  },
  {
    id: 'analyst',
    name: 'Analyst',
    role: 'Data Analyst',
    description: 'Analisa dados de campanhas, métricas e gera insights acionáveis.',
    icon: BarChart3,
    color: '#60A5FA',
    department: 'strategy',
  },
  {
    id: 'account',
    name: 'Account',
    role: 'Account Manager',
    description: 'Gestão de relacionamento e comunicação com clientes.',
    icon: Users,
    color: '#38BDF8',
    department: 'strategy',
  },
  {
    id: 'media-buyer',
    name: 'CELO',
    role: 'Media Buyer',
    description: 'Gestão de tráfego pago, otimização de campanhas Meta/Google Ads.',
    icon: TrendingUp,
    color: '#FF6B35',
    department: 'strategy',
  },

  // Creative
  {
    id: 'copy-chef',
    name: 'Copy Chef',
    role: 'Copy Strategist',
    description: 'Orquestra copywriters especialistas (Halbert, Ogilvy, Wiebe, Georgi).',
    icon: Feather,
    color: '#F472B6',
    department: 'creative',
  },
  {
    id: 'halbert',
    name: 'Halbert',
    role: 'Direct Response Copy',
    description: 'Copywriting Gary Halbert-style. Boron Letters, template 13 elementos.',
    icon: ScrollText,
    color: '#E879F9',
    department: 'creative',
  },
  {
    id: 'designer',
    name: 'Luna',
    role: 'Creative Designer',
    description: 'Pipeline criativo, Quality Gate 7 critérios, presets visuais.',
    icon: Paintbrush,
    color: '#C084FC',
    department: 'creative',
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Social Media Content',
    description: 'Conteúdo @byericsantos, voz do Eric, formatos F1-F5, swipe files.',
    icon: Sparkles,
    color: '#A78BFA',
    department: 'creative',
  },

  // Tech & Data
  {
    id: 'dev',
    name: 'Dev',
    role: 'Full-Stack Developer',
    description: 'Implementação de features, APIs, integrações e automações.',
    icon: Code2,
    color: '#34D399',
    department: 'tech',
  },
  {
    id: 'architect',
    name: 'Architect',
    role: 'Solution Architect',
    description: 'Arquitetura de sistemas, decisões técnicas, trade-offs.',
    icon: Brain,
    color: '#2DD4BF',
    department: 'tech',
  },
  {
    id: 'data-engineer',
    name: 'Data Engineer',
    role: 'Data Engineer',
    description: 'Pipelines de dados, schemas, Joe Reis playbook, lifecycle-first.',
    icon: Workflow,
    color: '#4ADE80',
    department: 'tech',
  },
  {
    id: 'qa',
    name: 'QA',
    role: 'Quality Assurance',
    description: 'Testes automatizados, validação de qualidade, edge cases.',
    icon: TestTube2,
    color: '#22D3EE',
    department: 'tech',
  },
  {
    id: 'devops',
    name: 'Gage',
    role: 'DevOps Engineer',
    description: 'Infra, deploy, PM2, Docker, MCP servers, CI/CD.',
    icon: Landmark,
    color: '#6EE7B7',
    department: 'tech',
  },

  // Operations
  {
    id: 'alex',
    name: 'Alex',
    role: 'Project Documentor',
    description: 'Único criador de tasks ClickUp. Telegram bot, documentação.',
    icon: FileText,
    color: '#5B8DEF',
    department: 'operations',
  },
  {
    id: 'ghl-maestro',
    name: 'GHL Maestro',
    role: 'GoHighLevel Specialist',
    description: 'Automações GHL, workflows, webhooks, Stevo integration.',
    icon: Bot,
    color: '#FF9800',
    department: 'operations',
  },
  {
    id: 'follow-up-specialist',
    name: 'Follow-Up',
    role: 'Follow-Up Specialist',
    description: 'Sequências de reativação 6 meses, WhatsApp/email, Russell Brunson.',
    icon: MessageSquare,
    color: '#F97316',
    department: 'operations',
  },
  {
    id: 'prospect-ig',
    name: 'IRIS',
    role: 'Instagram Prospector',
    description: 'Prospecção via Instagram DM, scoring de leads, pipeline.',
    icon: Instagram,
    color: '#AB47BC',
    department: 'operations',
  },
  {
    id: 'scribe',
    name: 'Scribe',
    role: 'Meeting Transcriber',
    description: 'Transcrição Groq Whisper, extração de inteligência de reuniões.',
    icon: Megaphone,
    color: '#EAB308',
    department: 'operations',
  },
  {
    id: 'legal',
    name: 'Legal',
    role: 'Legal Advisor',
    description: 'Contratos, termos de serviço, compliance e questões jurídicas.',
    icon: Shield,
    color: '#94A3B8',
    department: 'operations',
  },
  {
    id: 'sm',
    name: 'SM',
    role: 'Scrum Master',
    description: 'Facilitação de cerimônias, remoção de impedimentos, métricas ágeis.',
    icon: UserCheck,
    color: '#FB7185',
    department: 'operations',
  },
]
